# Generated by Django 2.2.6 on 2019-10-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('surat', 'Surat'), ('pune', 'Pune'), ('mumbai', 'Mumbai')], max_length=40, null=True),
        ),
    ]
