# Generated by Django 2.2.6 on 2019-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('0', 'User'), ('1', 'Dealer')], max_length=1, null=True),
        ),
    ]
