# Generated by Django 2.2.6 on 2019-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('dealer', 'Dealer')], max_length=1, null=True),
        ),
    ]
