# Generated by Django 2.2.6 on 2019-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20191011_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('dealer', 'Dealer')], max_length=8, null=True),
        ),
    ]
