# Generated by Django 2.2.6 on 2019-10-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
