# Generated by Django 2.2.6 on 2019-11-01 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcategory', to='admin_owner.Maincategory'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='product_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory-images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproduct', models.CharField(max_length=40, null=True)),
                ('brand_name', models.CharField(max_length=30, null=True)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('prod_image', models.ImageField(upload_to='product-images/')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='admin_owner.Subcategory')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='admin_owner.Maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Post_advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40, null=True)),
                ('price', models.IntegerField()),
                ('contact_supplier', models.IntegerField()),
                ('prod_image', models.ImageField(upload_to='addvertise/')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_advertise', to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_advertise', to='admin_owner.Subcategory')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_advertise', to='admin_owner.Maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('blog_desc', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blogimages/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('full_desc', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Reject')], default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
