# Generated by Django 2.2.6 on 2019-11-01 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_owner', '0002_auto_20191101_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to='admin_owner.Maincategory'),
        ),
    ]
