# Generated by Django 2.2.6 on 2019-11-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_owner', '0003_blog_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='admin_owner.Subcategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='admin_owner.Maincategory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subproduct',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
