# Generated by Django 2.2.6 on 2019-11-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_owner', '0004_auto_20191101_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='product_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='cat_blog',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
