# Generated by Django 2.2.6 on 2019-11-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_owner', '0005_auto_20191101_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
