# Generated by Django 2.2.6 on 2019-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Send'), (1, 'Recieve'), (2, 'Reject')], default=0),
        ),
    ]
