# Generated by Django 2.2.6 on 2019-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='farmer_name',
            field=models.CharField(help_text='Name of the sender', max_length=120),
        ),
    ]
