# Generated by Django 2.2.6 on 2019-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_contact_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
