# Generated by Django 2.2.6 on 2019-11-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complate_message',
            new_name='complaint_message',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complate_type',
            new_name='complaint_type',
        ),
    ]
