# Generated by Django 2.2.6 on 2019-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20191121_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_message',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
