# Generated by Django 2.2.6 on 2019-11-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20191121_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
