# Generated by Django 2.2.6 on 2019-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20191121_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
